# Generated by Django 4.2.1 on 2023-06-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_remove_order_used_coupon_order_copuon_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
