# Generated by Django 4.2.1 on 2023-06-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_color_title_alter_generalcategory_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
